development:
  adapter: mysql
  database: develop_progress
  username: progress
  password: progress
  host: localhost
test:
  adapter: mysql
  database: test_progress
  username: progress
  password: progress
  host: localhost
production:
  adapter: mysql
  database: progress
  username: progress
  password: progress
  host: localhost
